### ISSUE TITLE
Trinket M0 pins 3 and 4 as well as Gemma M0 pin 2 do not work

### ISSUE THREAD

**Issue by cyborg5** [cyborg5/IRLib2#44]
I'm opening this issue myself to highlight a known problem. I cannot get PWM output on Trinket M0 pin 3. It is connected to hardware pin PA07 which is identical to pin 9 on Arduino Zero, Arduino M0 Pro, and Adafruit Feather M0 boards all of which work. But for some reason PA07 on the Trinket M0 does not work. Similarly Trinket M0 pin 4 is connected to hardware pin PA06 which is identical to pin 8 on the Arduino Zero and Arduino M0 Pro and those work perfectly but not on the Trinket M0.

The Gemma M0 should support PWM on its pin 2 but I cannot get it to work. It's connected to hardware pin PA05 which I have not used elsewhere but the code should still work.

Anyone with suggestions your help is much appreciated. We went ahead and released the code because pin 0 works okay on both boards and 2 works okay on the Trinket M0.

**Comment by muawijhe** [comment]
Hi @cyborg5 !

First of all, thanks for releasing the library. Very nice indeed.

I would like to ask you the following question:

[Following the drawings from adafruit](https://cdn-learn.adafruit.com/assets/assets/000/049/778/large1024/adafruit_products_Adafruit_Trinket_M0.png?1514756138) it seems that all pins are PWM available except #1.
Also from the same diagram it seems that all pins are INTERRUPT compatible, except pin #0.

I am trying to make a small project using both IR Led for transmission and IR Receiver (1838 serie).

For such a project, based on your library and on the Trinket M0 hardware, could you please reccomend
a proper configuration for the h-files?

Apparently, trying to compile an example code highlights that the selected PWM PIN is #3 (default case)... hence I have to assume that the configuration for the Trinket M0 has not been pushed?

Hoping you will reply soon,

Thanks again

V.

**Comment by l8gravely** [comment]
This is really really late, but on the GemmaM0, are you talking about A1/D2, A2/D0 or D1/A0 pin on the board when you talk about this issue?  I'll track it down more myself once I'm home and can look at my working board, but current test setup in front of me gave me:

Traceback (most recent call last):
  File "main.py", line 130, in <module>
  File "/lib/IRLib_P01_NECs.py", line 18, in send
  File "/lib/IRLibSendBase.py", line 55, in sendGeneric
  File "/lib/IRLibSendBase.py", line 14, in enableIROut
ValueError: Invalid pin

Adafruit CircuitPython 2.2.4 on 2018-03-07; Adafruit Gemma M0 with samd21e18


Where my initialization code looks like this:

     myS = IRLib_P01_NECs.IRsendNEC(board.D1)

Where it had worked properly with board.D0 before.  Time to investigate more.  Thanks for your work!
